---
- name: Download splunk forwarder
  gather_facts: yes
  hosts: 35.177.209.90
  become: yes
  become_method: sudo
  tasks:
    - name: Install necessary packages
      package:
        name: "{{item}}"
        state: latest
      with_items:
       - wget
       - unzip
      ignore_errors: true
    - name: downloand forwarder
      shell: wget -O splunkforwarder-8.0.3-a6754d8441bf-Linux-x86_64.tgz 'https://www.splunk.com/bin/splunk/DownloadActivityServlet?architecture=x86_64&platform=linux&version=8.0.3&product=universalforwarder&filename=splunkforwarder-8.0.3-a6754d8441bf-Linux-x86_64.tgz&wget=true'
    - name: unzip forwarder
      command: tar xvzf splunkforwarder-8.0.3-a6754d8441bf-Linux-x86_64.tgz -C /opt
    - name: make user and pass
      shell: touch /root/splunkforwarder/etc/system/local/user-seed.conf
    - name: give user admin and pass block in /root/splunkforwarder/etc/system/local/user-seed.conf
      blockinfile:
        path: /root/splunkforwarder/etc/system/local/user-seed.conf
        block: |
          [user-info]
           USERNAME = admin
           PASSWORD = somepasswrd
    - name: Start Splunk Forwarder
      command: cd /opt/splunkforwarder/bin/ && ./splunk restart --accept-license
    - name: Set forward-server
      command: cd /opt/splunkforwarder/bin/ && ./splunk add forward-server 18.130.133.195:9997 -auth admin:somepassword
    - name: Add monitor
      command: cd /opt/splunkforwarder/bin/ && ./splunk add monitor /var/log/messages
    - name: Enable Boot Start
      command: cd /opt/splunkforwarder/bin/ && ./splunk enable boot-start
    - name: Restart Splunk forwarder
      command: cd /opt/splunkforwarder/bin/ && ./splunk restart
